NEI <- readRDS("summarySCC_PM25.rds")
SCCF <- readRDS("Source_Classification_Code.rds")
bNEI <- subset(NEI,fips == "24510")
mSCC <- subset(SCCF,grepl("motor", Short.Name, ignore.case = TRUE), drop= TRUE)
mNEI <- subset(bNEI,SCC %in% mSCC[,1])
agg <- aggregate(mNEI[,c("Emissions")], list(mNEI$year), sum)
plot5 <- png("plot5.png", width=480, height = 480)
names(agg) <- c("year","Emissions")
qplot(year,Emissions,data = agg,geom = c("point","smooth"))
dev.off()
