NEI <- readRDS("summarySCC_PM25.rds")
SCCF <- readRDS("Source_Classification_Code.rds")
bNEI <- subset(NEI,(fips == "24510") | (fips == "06037"))
##lNEI <- subset(NEI,fips == 06037)
mSCC <- subset(SCCF,grepl("motor", Short.Name, ignore.case = TRUE), drop= TRUE)
mNEI <- subset(bNEI,SCC %in% mSCC[,1])
#mlNEI <- subset(lNEI,SCC %in% mSCC[,1])
agg <- aggregate(mNEI[,c("Emissions")], list(mNEI$year,mNEI$fips), sum)
plot6 <- png("plot6.png", width=480, height = 480)
names(agg) <- c("year","city","Emissions")
qplot(year,Emissions,data = agg,facets=. ~ city, geom = c("point","smooth"))
dev.off()
