NEI <- readRDS("summarySCC_PM25.rds")
agg <- aggregate(NEI[,c("Emissions")], list(NEI$year), sum)
plot1 <- png("plot1.png", width=480, height = 480)
with(agg,plot(Group.1,x, type="o",xlab="year",ylab="PM2.5"))
dev.off()
